name: Deploy Swagger Docs to GitHub Pages

on:
  push:
    branches:
      - main # Ou a branch que você usa como principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Pode ajustar para a sua versão do Node.js
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate Swagger spec
        run: npm run swagger

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4